% This script generates unique codes for each EPA outdoor air quality monitoring site
% by combining "State Code", "County Code", and "Site Number" fields from the original
% EPA site description. The unique site codes, referred to as "Site_id", are used
% as a key for joining pollutant component data tables to the site 
% description CSV file named "Site_properties.csv", generated by this script.
% The original site description data is available at:
% "https://aqs.epa.gov/aqsweb/airdata/aqs_sites.zip"

% Clear workspace
clc;
clear;

% Read the site description data from disc
siteDescriptionFile = '...\aqs_sites.csv';
site = readtable(siteDescriptionFile, 'FileType', 'text', 'Delimiter', ',', 'VariableNamingRule', 'preserve');

% Rename the first three columns for clarity
site.Properties.VariableNames{1} = 'StateCode';
site.Properties.VariableNames{2} = 'CountyCode';
site.Properties.VariableNames{3} = 'SiteNumber';

% Define format specifications for State, County, and Site codes
formatSpecState = '%02.0f';
formatSpecCounty = '%03.0f';
formatSpecSite = '%04.0f';

% Generate the unique Site_id by concatenating StateCode, CountyCode, and SiteNumber
site.Site_id = append(string(num2str(site.StateCode, formatSpecState)), ...
    string(num2str(site.CountyCode, formatSpecCounty)), string(num2str(site.SiteNumber, formatSpecSite)));

% Replace any spaces with zeros and convert to double
site.Site_id = double(strrep(site.Site_id, ' ', '0'));

% Restore original column names for readability
site.Properties.VariableNames{1} = 'State Code';
site.Properties.VariableNames{2} = 'County Code';
site.Properties.VariableNames{3} = 'Site Number';

% Write the updated table with Site_id to a new CSV file
outputFile = '...\Site_properties.csv';
writetable(site, outputFile, 'Delimiter', ',', 'WriteVariableNames', true);

