% This script processes anthropogenic annual fluxes (kg/m^2/s) and 
% total emissions (Tg) of PM10, PM2.5, and NOx.
% EDGARv6_Glb_0.1x0.1_anthro Data in Grib format were downloaded from ECCAD 
% (Emissions of atmospheric Compounds and Compilation of Ancillary Data)
% "https://eccad.sedoo.fr/#/catalogue" for the years 1970 to 2018 
% (Janssens-Maenhout, G., Crippa, M., Guizzardi, D., Dentener, F., Muntean, M., 
% Pouliot, G., Keating, T., Zhang, Q., Kurokawa, J., Wankmüller, R., Denier 
% van der Gon, H., Kuenen, J. J. P., Klimont, Z., Frost, G., Darras, S., Koffi, 
% B., and Li, M.2015HTAP_v2.2: a mosaic of regional and global emission grid maps 
% for 2008 and 2010 to study hemispheric transport of air pollutionAtmos.
% Chem. Phys.15,11411-11432,2015).
% The script also extrapolates data to estimate emissions for the year 2019.

% Clear workspace
clc;
clear;

%% Preparing Site Data for Sampling
% Adjusting longitude for EEA and EPA sites to match the global extent of EDGAR data

% Process EEA sites
% The  site description of EEA station data is available at:
% "http://aq-data.ricardo-aea.com/R_data/saqgetr/helper_tables/sites_table.csv.gz"
optsEEA = detectImportOptions('...\sites_table.csv');
optsEEA = setvartype(optsEEA, 'site', 'string');
EEASites = readtable('...\sites_table.csv', optsEEA);
EEASites.longitude(EEASites.longitude < 0) = EEASites.longitude(EEASites.longitude < 0) + 360;
EEASites = EEASites(:, {'site', 'latitude', 'longitude'});
EEASites.Origin = repmat("EEA", height(EEASites), 1);

% Process EPA sites
% Generated by "Site_code_generation_EPA" script
optsEPA = detectImportOptions('...\Site_properties.csv');
optsEPA = setvartype(optsEPA, 'Site_id', 'string');
EPASites = readtable('...\Site_properties.csv', optsEPA);
EPASites.Longitude(EPASites.Longitude < 0) = EPASites.Longitude(EPASites.Longitude < 0) + 360;
EPASites = renamevars(EPASites, {'Site_id', 'Latitude', 'Longitude'}, {'site', 'latitude', 'longitude'});
EPASites.Origin = repmat("EPA", height(EPASites), 1);
EPASites.site = string(EPASites.site);

% Combine EEA and EPA sites
CombinedSites = vertcat(EEASites, EPASites);
writetable(CombinedSites, '...\EPA_EEA_sites_prepared_for_edgar_extent.csv', ...
    'Delimiter', ',', 'WriteVariableNames', true);

% Using the QGIS "Sample raster values" tool, Edgar emissions values were extracted
% at the locations of EEA and EPA stations for each year. The output for each component
% is a table with the first column as 'site', the second as 'Origin', and the third to
% 51st columns containing the component emission data for each year from 1970 to 2018.

%% Extrapolating Data from 2013-2018 to Estimate 2019 Emissions
% Process for PM2.5, PM10, and NOx

components = {'PM25','PM10','NOx'};
for i = 1:length(components)
    component = string(components{i});
    % Import the output of QGIS "Sample raster values" tool
    dataFile = strcat('...',...
        '/EDGARv6_Glb_anthro_', component, '_yearly_sum_sectors_flux_kg_m-2_s-1.txt');
    opts = detectImportOptions(dataFile);
    opts = setvartype(opts, 'site', 'string');
    T = readtable(dataFile, opts);

    % Standardize missing values and select relevant years
    T.Properties.VariableNames(3:end) = cellstr(append('yr_', string(1970:2018)));
    T = standardizeMissing(T, 9.9692100e+36);
    T = T(:, [1:2, 33:end]); % 2000 - 2018

    % Extrapolate to estimate 2019 data
    T.yr_2019 = table2array(rowfun(@(x1, x2, x3, x4, x5, x6) interp1(1:6, [x1, x2, x3, x4, x5, x6], 7, 'linear', 'extrap'), T, ...
        'InputVariables', {'yr_2013', 'yr_2014', 'yr_2015', 'yr_2016', 'yr_2017', 'yr_2018'}));

    % Write extrapolated data to a new file
    outputFile = strcat('...\EDGARv6_Glb_anthro_', component, ...
        '_yearly_sum_sectors_flux_kg_m-2_s-1_2000_2019.csv');
    writetable(T, outputFile, 'Delimiter', ',', 'WriteVariableNames', true);
end
